name: posts_client
description: Personal website and blog client.
repository: https://github.com/nikeorever/posts_client

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_markdown: ^0.4.4
  url_launcher: ^5.5.2
  wedzera: ^0.1.0
  google_fonts: ^1.1.0
  provider: ^4.3.1
  built_collection: ^4.3.2
  built_value: ^7.1.0
  json_serializable: ^3.4.0
  dartrofit: ^1.0.0
  dartrofit_adapter_rx: ^1.0.0
  dartrofit_converter_xml: ^1.0.0
  dartrofit_converter_json: ^1.0.0
  timeconsuming_page_builder: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  dartrofit_generator: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/nikeo.jpeg
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Black.otf
          weight: 900
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Regular.otf
          weight: 400
          style: normal
        - asset: assets/fonts/Noto_Sans_SC/NotoSansSC-Thin.otf
          weight: 100

