name: posts_client
description: Personal website and blog client.
repository: https://github.com/nikeorever/posts_client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_markdown: ^0.4.2
  wedzera: ^0.1.0
  google_fonts: ^1.1.0
  provider: ^4.3.1
  built_collection: ^4.3.2
  built_value: ^7.1.0
  json_serializable: ^3.4.0
  dartrofit:
    path: /home/xianxueliang/IdeaProjects/dartrofit/dartrofit
  dartrofit_adapter_rx:
    path: /home/xianxueliang/IdeaProjects/dartrofit/dartrofit_adapters/adapter_rx
  dartrofit_converter_xml:
    path: /home/xianxueliang/IdeaProjects/dartrofit/dartrofit_converters/converter_xml
  dartrofit_converter_json:
    path: /home/xianxueliang/IdeaProjects/dartrofit/dartrofit_converters/converter_json


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0
  dartrofit_generator:
    path: /home/xianxueliang/IdeaProjects/dartrofit/dartrofit_generator

flutter:

  uses-material-design: true
  assets:
    - assets/images/nikeo.jpeg
